version: '3.7'
services:
  database:
    build: ./docker-misc/postgres/
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=db #db for webapp
        - RUNNER_DB=runner_db #db for runner
    ports:
      - '5432:5432' #meant for script to add/update challs

  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - "webapp"
    volumes:
      - ./docker-misc/caddy/Caddyfile:/etc/caddy/Caddyfile


#    nginx:
#      container_name: nginx
#      hostname: nginx
#      build: ./docker-misc/nginx/
#      restart: always
#      ports:
#        - "80:80"
#        - "443:443"
#      links:
#        - "webapp"
  webapp:
    build:
      context: ./
      dockerfile: ./Dockerfile.prod
    restart: always
    volumes:
      - /app/node_modules
    depends_on:
      - "runner"
    links:
      - "database"
      - "runner"
  runner:
    container_name: runner
    build: ./runner
    restart: always
    depends_on:
      - "database"
    links:
      - "database"
    ports:
      - '10000:10000' #meant for script at portainer within VPC to communicate.
volumes:
  postgres:
